Restaurant/Areas/Admin/ViewModels/MasterMenuViewmodel.cs
using Restaurant.Models;

namespace Restaurant.Areas.Admin.ViewModels
{
    public class MasterMenuViewmodel : BaseEntity
    {
        public int MasterMenuId { get; set; }

        public string MasterMenuName { get; set; } = null!;

        public string MasterMenuUrl { get; set; } = null!;
    }
}

Restaurant/Models/MasterMenu.cs
using System;
using System.Collections.Generic;

namespace Restaurant.Models
{
    public class MasterMenu : BaseEntity
    {
        public int MasterMenuId { get; set; }

        public string MasterMenuName { get; set; }

        public string MasterMenuUrl { get; set; }
    }
}

Restaurant/Areas/Admin/Controllers/MasterMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Areas.Admin.ViewModels;
using Restaurant.Models;
using Restaurant.Models.Repository;

namespace Restaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterMenuController : Controller
    {
        public IRepository<MasterMenu> MasterMenu { get; }
        public UserManager<AppUser> UserManager { get; }

        public MasterMenuController(IRepository<MasterMenu> _masterMenu, UserManager<AppUser> _userManager)
        {
            MasterMenu = _masterMenu;
            UserManager = _userManager;
        }
        // GET: MasterMenuController
        public ActionResult Index()
        {
            var data = MasterMenu.View();
            return View(data);
        }

        public ActionResult Active(int id)
        {
            var data = MasterMenu.Find(id);
            data.EditDate = DateTime.Now;
            data.EditUser = User.Identity.Name;
            MasterMenu.Active(id, data);
            return RedirectToAction(nameof(Index));
        }

        // GET: MasterMenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MasterMenuViewmodel collection)
        {
            try
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var data = new MasterMenu
                {
                    MasterMenuId = collection.MasterMenuId,
                    MasterMenuName = collection.MasterMenuName,
                    MasterMenuUrl = collection.MasterMenuUrl,
                    CreateUser = user.Id,
                    CreateDate = DateTime.Now,
                    IsActive = true
                };
                MasterMenu.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterMenuController/Edit
        public ActionResult Edit(int id)
        {
            var data = MasterMenu.Find(id);
            MasterMenuViewmodel masterMenuViewModel = new MasterMenuViewmodel();
            masterMenuViewModel.MasterMenuId = data.MasterMenuId;
            masterMenuViewModel.MasterMenuName = data.MasterMenuName;
            masterMenuViewModel.MasterMenuUrl = data.MasterMenuUrl;
            masterMenuViewModel.CreateUser = data.CreateUser;
            masterMenuViewModel.CreateDate = data.CreateDate;
            return View(masterMenuViewModel);
        }

        // POST: MasterMenuController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MasterMenuViewmodel collection)
        {
            try
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var data = new MasterMenu
                {
                    MasterMenuId = collection.MasterMenuId,
                    MasterMenuName = collection.MasterMenuName,
                    MasterMenuUrl = collection.MasterMenuUrl,
                    CreateUser = collection.CreateUser,
                    CreateDate = collection.CreateDate,
                    EditUser = user.Id,
                    EditDate = DateTime.Now,
                };
                MasterMenu.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterMenuController/Delete
        public ActionResult Delete(int Delete)
        {
            MasterMenu.Delete(Delete, new Models.MasterMenu { EditUser = User.Identity.Name, EditDate = DateTime.Now });
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurant/Areas/Admin/Views/MasterMenu/Create.cshtml
@model Restaurant.Areas.Admin.ViewModels.MasterMenuViewmodel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <h2>MasterMenu</h2>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterMenu">MasterMenu</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="MasterMenuId" class="form-control" type="hidden" value="0" />
    <div class="row m-0">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterMenuName" class="form-label"></label>
                <input asp-for="MasterMenuName" class="form-control" placeholder="Enter Name" />
                <span asp-validation-for="MasterMenuName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterMenuUrl" class="form-label"></label>
                <input asp-for="MasterMenuUrl" class="form-control" placeholder="Enter URL" />
                <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="text-end">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</form>

Restaurant/Areas/Admin/Views/MasterMenu/Edit.cshtml
@model Restaurant.Areas.Admin.ViewModels.MasterMenuViewmodel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <h2>MasterMenu</h2>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterMenu">MasterMenu</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MasterMenuId" />
    <input type="hidden" asp-for="CreateUser" />
    <input type="hidden" asp-for="CreateDate" />
    <div class="row m-0">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterMenuName" class="form-label"></label>
                <input asp-for="MasterMenuName" class="form-control" />
                <span asp-validation-for="MasterMenuName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterMenuUrl" class="form-label"></label>
                <input asp-for="MasterMenuUrl" class="form-control" />
                <span asp-validation-for="MasterMenuUrl" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="text-end">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</form>

Restaurant/Areas/Admin/Views/MasterMenu/Index.cshtml
@model IEnumerable<Restaurant.Models.MasterMenu>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <h1>Restaurant</h1>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">MasterMenu</li>
        </ol>
    </nav>
</div>

<div class="text-end">
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</div>

<h3></h3>
<table class="datatable">
    <thead>
        <tr>
            @*<th>
                Menu Id
            </th>*@
            <th>
                Menu Name
            </th>
            <th>
                Menu Url
            </th>
            <th>operations</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.MasterMenuId)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.MasterMenuName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MasterMenuUrl)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.MasterMenuId"><i style="color:forestgreen;font-size:20px" class=" ri- bxs-edit"></i></a> |
                    <a class="btnDelete" href="#" data-toggle="modal" data-target="#exampleModal" data-paths="@Url.ActionLink("Delete","MasterMenu",new{Delete=item.MasterMenuId})"><i style="color:red;font-size:20px" class=" ri-close-circle-line"> </i></a>|
                    @if (item.IsActive)
                    {
                        <a asp-action="Active" asp-route-id="@item.MasterMenuId">
                            <i class="ri-eye-fill " style="font-size:20px"></i>
                        </a>
                    }
                    else
                    {
                        <a asp-action="Active" asp-route-id="@item.MasterMenuId">
                            <i class=" ri-eye-off-line" style="font-size:20px"></i>
                        </a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are You sure want to delete this Record ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="btnClose" data-dismiss="modal">Close</button>
                <input type="button" class="btn btn-danger" value="Delete" id="btnConfirmDelete" />
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var urlPathDelete = "";

        $(".btnDelete").click(function () {
            console.log($(this).data("paths"));
            urlPathDelete = $(this).data("paths");
            console.log(urlPathDelete);
        });

        $("#btnConfirmDelete").click(function () {
            window.location = urlPathDelete;
        });
    });
</script>