Restaurant/Areas/Admin/ViewModels/MasterWorkingHourViewModel.cs
using Restaurant.Models;

namespace Restaurant.Areas.Admin.ViewModels
{
    public class MasterWorkingHourViewModel : BaseEntity
    {
        public int MasterWorkingHourId { get; set; }

        public string MasterWorkingHourIdName { get; set; }

        public string MasterWorkingHourIdTimeFormTo { get; set; }
    }
}

Restaurant/Models/MasterWorkingHour.cs
using System;
using System.Collections.Generic;

namespace Restaurant.Models
{
    public class MasterWorkingHour : BaseEntity
    {
        public int MasterWorkingHourId { get; set; }

        public string MasterWorkingHourIdName { get; set; }

        public string MasterWorkingHourIdTimeFormTo { get; set; }
    }
}

Restaurant/Areas/Admin/Controllers/MasterWorkingHourController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Areas.Admin.ViewModels;
using Restaurant.Models;
using Restaurant.Models.Repository;

namespace Restaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MasterWorkingHourController : Controller
    {
        public IRepository<MasterWorkingHour> MasterWorkingHour { get; }
        public UserManager<AppUser> UserManager { get; }

        public MasterWorkingHourController(IRepository<MasterWorkingHour> _masterWorkingHour, UserManager<AppUser> _userManager)
        {
            MasterWorkingHour = _masterWorkingHour;
            UserManager = _userManager;
        }
        // GET: MasterWorkingHourController
        public ActionResult Index()
        {
            var data = MasterWorkingHour.View();
            return View(data);
        }

        public ActionResult Active(int id)
        {
            var data = MasterWorkingHour.Find(id);
            data.EditDate = DateTime.Now;
            data.EditUser = User.Identity.Name;
            MasterWorkingHour.Active(id, data);
            return RedirectToAction(nameof(Index));
        }

        // GET: MasterWorkingHourController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterWorkingHourController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MasterWorkingHourViewModel collection)
        {
            try
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var data = new MasterWorkingHour
                {
                    MasterWorkingHourId = collection.MasterWorkingHourId,
                    MasterWorkingHourIdName = collection.MasterWorkingHourIdName,
                    MasterWorkingHourIdTimeFormTo = collection.MasterWorkingHourIdTimeFormTo,
                    CreateUser = user.Id,
                    CreateDate = DateTime.Now,
                    IsActive = true
                };
                MasterWorkingHour.Add(data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterWorkingHourController/Edit
        public ActionResult Edit(int id)
        {
            var data = MasterWorkingHour.Find(id);
            MasterWorkingHourViewModel masterWorkingHourViewModel = new MasterWorkingHourViewModel();
            masterWorkingHourViewModel.MasterWorkingHourId = data.MasterWorkingHourId;
            masterWorkingHourViewModel.MasterWorkingHourIdName = data.MasterWorkingHourIdName;
            masterWorkingHourViewModel.MasterWorkingHourIdTimeFormTo = data.MasterWorkingHourIdTimeFormTo;
            masterWorkingHourViewModel.CreateUser = data.CreateUser;
            masterWorkingHourViewModel.CreateDate = data.CreateDate;
            return View(masterWorkingHourViewModel);
        }

        // POST: MasterWorkingHourController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MasterWorkingHourViewModel collection)
        {
            try
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var data = new MasterWorkingHour
                {
                    MasterWorkingHourId = collection.MasterWorkingHourId,
                    MasterWorkingHourIdName = collection.MasterWorkingHourIdName,
                    MasterWorkingHourIdTimeFormTo = collection.MasterWorkingHourIdTimeFormTo,
                    CreateUser = collection.CreateUser,
                    CreateDate = collection.CreateDate,
                    EditUser = user.Id,
                    EditDate = DateTime.Now,
                };
                MasterWorkingHour.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MasterWorkingHourController/Delete
        public ActionResult Delete(int Delete)
        {
            MasterWorkingHour.Delete(Delete, new Models.MasterWorkingHour { EditUser = User.Identity.Name, EditDate = DateTime.Now });
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurant/Areas/Admin/Views/MasterWorkingHour/Create.cshtml
@model Restaurant.Areas.Admin.ViewModels.MasterWorkingHourViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="pagetitle">
    <h2>MasterWorkingHour</h2>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterWorkingHour">MasterWorkingHour</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>
</div>

<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="MasterWorkingHourId" class="form-control" type="hidden" value="0" />
    <div class="row m-0">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterWorkingHourIdName" class="form-label"></label>
                <input asp-for="MasterWorkingHourIdName" class="form-control" />
                <span asp-validation-for="MasterWorkingHourIdName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterWorkingHourIdTimeFormTo" class="form-label"></label>
                <input asp-for="MasterWorkingHourIdTimeFormTo" class="form-control" />
                <span asp-validation-for="MasterWorkingHourIdTimeFormTo" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="text-end">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</form>

Restaurant/Areas/Admin/Views/MasterWorkingHour/Edit.cshtml
@model Restaurant.Areas.Admin.ViewModels.MasterWorkingHourViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <h2>MasterWorkingHour</h2>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="MasterWorkingHour">MasterWorkingHour</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>

<form asp-action="Edit" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MasterWorkingHourId" />
    <input type="hidden" asp-for="CreateUser" />
    <input type="hidden" asp-for="CreateDate" />
    <div class="row m-0">
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterWorkingHourIdName" class="form-label"></label>
                <input asp-for="MasterWorkingHourIdName" class="form-control" />
                <span asp-validation-for="MasterWorkingHourIdName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label asp-for="MasterWorkingHourIdTimeFormTo" class="form-label"></label>
                <input asp-for="MasterWorkingHourIdTimeFormTo" class="form-control" />
                <span asp-validation-for="MasterWorkingHourIdTimeFormTo" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="text-end">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</form>

Restaurant/Areas/Admin/Views/MasterWorkingHour/Index.cshtml
@model IEnumerable<Restaurant.Models.MasterWorkingHour>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <h1>Restaurant</h1>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">MasterWorkingHour</li>
        </ol>
    </nav>
</div>

<div class="text-end">
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</div>

<h3></h3>
<table class="datatable">
    <thead>
        <tr>
            @*<th>
                MasterWorkingHour Id
            </th>*@
            <th>
                WorkingHour Name
            </th>
            <th>
                WorkingHour TimeFromTo
            </th>
            <th>operations</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.MasterWorkingHourId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.MasterWorkingHourIdName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MasterWorkingHourIdTimeFormTo)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.MasterWorkingHourId"><i style="color:forestgreen;font-size:20px" class=" ri- bxs-edit"></i></a> |
                    <a class="btnDelete" href="#" data-toggle="modal" data-target="#exampleModal" data-paths="@Url.ActionLink("Delete","MasterWorkingHour",new{Delete=item.MasterWorkingHourId})"><i style="color:red;font-size:20px" class=" ri-close-circle-line"> </i></a>|
                    @if (item.IsActive)
                    {
                        <a asp-action="Active" asp-route-id="@item.MasterWorkingHourId">
                            <i class="ri-eye-fill " style="font-size:20px"></i>
                        </a>
                    }
                    else
                    {
                        <a asp-action="Active" asp-route-id="@item.MasterWorkingHourId">
                            <i class=" ri-eye-off-line" style="font-size:20px"></i>
                        </a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are You sure want to delete this Record ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="btnClose" data-dismiss="modal">Close</button>
                <input type="button" class="btn btn-danger" value="Delete" id="btnConfirmDelete" />
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var urlPathDelete = "";

        $(".btnDelete").click(function () {
            console.log($(this).data("paths"));
            urlPathDelete = $(this).data("paths");
            console.log(urlPathDelete);
        });

        $("#btnConfirmDelete").click(function () {
            window.location = urlPathDelete;
        });
    });
</script>