Restaurant/Areas/Admin/ViewModels/TransactionNewsletterViewModel.cs
using Restaurant.Models;

namespace Restaurant.Areas.Admin.ViewModels
{
    public class TransactionNewsletterViewModel : BaseEntity
    {
        public int TransactionNewsletterId { get; set; }

        public string TransactionNewsletterEmail { get; set; }
    }
}

Restaurant/Models/TransactionNewsletter.cs
using System;
using System.Collections.Generic;

namespace Restaurant.Models
{
    public class TransactionNewsletter : BaseEntity
    {
        public int TransactionNewsletterId { get; set; }

        public string TransactionNewsletterEmail { get; set; }
    }
}

Restaurant/Areas/Admin/Controllers/TransactionNewsletterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Areas.Admin.ViewModels;
using Restaurant.Models;
using Restaurant.Models.Repository;

namespace Restaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TransactionNewsletterController : Controller
    {
        public IRepository<TransactionNewsletter> TransactionNewsletter { get; }
        public UserManager<AppUser> UserManager { get; }

        public TransactionNewsletterController(IRepository<TransactionNewsletter> _transactionNewsletter, UserManager<AppUser> _userManager)
        {
            TransactionNewsletter = _transactionNewsletter;
            UserManager = _userManager;
        }
        // GET: TransactionNewsletterController
        public ActionResult Index()
        {
            var data = TransactionNewsletter.View();
            return View(data);
        }

        // GET: TransactionNewsletterController/Edit
        public ActionResult Edit(int id)
        {
            var data = TransactionNewsletter.Find(id);
            TransactionNewsletterViewModel transactionNewsletterViewModel = new TransactionNewsletterViewModel();
            transactionNewsletterViewModel.TransactionNewsletterId = data.TransactionNewsletterId;
            transactionNewsletterViewModel.TransactionNewsletterEmail = data.TransactionNewsletterEmail;
            transactionNewsletterViewModel.CreateUser = data.CreateUser;
            transactionNewsletterViewModel.CreateDate = data.CreateDate;
            return View(transactionNewsletterViewModel);
        }

        // POST: TransactionNewsletterController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, TransactionNewsletterViewModel collection)
        {
            try
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var data = new TransactionNewsletter
                {
                    TransactionNewsletterId = collection.TransactionNewsletterId,
                    TransactionNewsletterEmail = collection.TransactionNewsletterEmail,
                    CreateUser = collection.CreateUser,
                    CreateDate = collection.CreateDate,
                    EditUser = user.Id,
                    EditDate = DateTime.Now,
                };
                TransactionNewsletter.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TransactionNewsletterController/Delete
        public ActionResult Delete(int Delete)
        {
            TransactionNewsletter.Delete(Delete, new Models.TransactionNewsletter { EditUser = User.Identity.Name, EditDate = DateTime.Now });
            return RedirectToAction(nameof(Index));
        }
    }
}

Restaurant/Areas/Admin/Views/TransactionNewsletter/Edit.cshtml
@model Restaurant.Areas.Admin.ViewModels.TransactionNewsletterViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <h2>TransactionNewsletter</h2>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="TransactionNewsletter">TransactionNewsletter</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="TransactionNewsletterId" />
    <input type="hidden" asp-for="CreateUser" />
    <input type="hidden" asp-for="CreateDate" />
    <div class="row m-0">
        <div class="col-4">
            <div class="form-group">
        <label asp-for="TransactionNewsletterEmail" class="form-label"></label>
        <input asp-for="TransactionNewsletterEmail" class="form-control" />
        <span asp-validation-for="TransactionNewsletterEmail" class="text-danger"></span>
    </div>
        </div>
    </div>
    <div class="text-end">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</form>

Restaurant/Areas/Admin/Views/TransactionNewsletter/Index.cshtml
@model IEnumerable<Restaurant.Models.TransactionNewsletter>

@{
    ViewData["Title"] = "Index";
}

<div class="pagetitle">
    <h1>Restaurant</h1>
    <br />
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">TransactionNewsletter</li>
        </ol>
    </nav>
</div>

@*<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>*@

<h3></h3>
<table class="datatable">
    <thead>
        <tr>
            @*<th>
                Newsletter Id
            </th>*@
            <th>
                Newsletter Email
            </th>
            <th>operations</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.TransactionNewsletterId)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.TransactionNewsletterEmail)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.TransactionNewsletterId"><i style="color:forestgreen;font-size:20px" class=" ri- bxs-edit"></i></a> |
                    <a class="btnDelete" href="#" data-toggle="modal" data-target="#exampleModal" data-paths="@Url.ActionLink("Delete","TransactionNewsletter",
                    new{Delete=item.TransactionNewsletterId})"><i style="color:red;font-size:20px" class=" ri-close-circle-line"> </i></a>
            </td>
        </tr>
}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are You sure want to delete this Record ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="btnClose" data-dismiss="modal">Close</button>
                <input type="button" class="btn btn-danger" value="Delete" id="btnConfirmDelete" />
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var urlPathDelete = "";

        $(".btnDelete").click(function () {
            console.log($(this).data("paths"));
            urlPathDelete = $(this).data("paths");
            console.log(urlPathDelete);
        });

        $("#btnConfirmDelete").click(function () {
            window.location = urlPathDelete;
        });
    });
</script>